### ISSUE TITLE
isLightTheme attributed redefined

### ISSUE THREAD

**Issue by gkipnis** [commonsguy/cwac-mediarouter#6]
res/values/attrs.xml defines an "isLightTheme" attribute and uses it in res/values/styles.xml and app/MediaRouterThemeHelper.java

This attribute is also defined in the adobe creative-sdk library, resulting in an attribute redefinition error when using creative-sdk and cwac-mediarouter libraries in the same project.

I cloned the repository to my local machine and renamed this attribute. I am now able to build the project with both libraries in it. It would be great if I didn't have to have my own version of cwac-mediarouter and have you guys rename this attribute to something else. I simply changed it to "mrIsLightTheme".

**Comment by commonsguy** [comment]
Sorry, but this project is a strict port of `mediarouter-v7`, with the bare minimum changes to allow it to work with the native action bar. If `mediarouter-v7` names something `isLightTheme`, then this port will have it named `isLightTheme`.

Now, I do need to update this project to match the latest `mediarouter-v7`, and it's entirely possible that this attribute has been renamed there, as presumably the same collision would be seen between `creative-sdk` and `mediarouter-v7`.

**Comment by gkipnis** [comment]
How can I check if Goodle's mediearouter-v7 contains this attribute? I never tried compiling creative-sdk with mediarouter-v7, because of the AppCompActivity requirement, which resulted in too many changes. But if mediarouter-v7, does contain "isLightTheme" attribute, then I can try filing a bug with Adobe.
Thanks,Gary
 


     On Saturday, September 12, 2015 6:10 PM, Mark Murphy <notifications@github.com> wrote:
   

 Closed #6.—

**Comment by commonsguy** [comment]
If you have the Android Support library and the Android Support repository downloaded from SDK Manager, the source to `mediarouter-v7` is in `$ANDROID_SDK/extras/android/support/v7/mediarouter`, where `$ANDROID_SDK` is wherever your Android SDK is installed.

It does look like they got rid of that attribute. I'm aiming to update this project's cross-port this coming week to match the 23.0.1 release of `mediarouter-v7`. Once that's out, you can try to move over to it, and it should clear up your problem.
